# Generated by Django 4.2.4 on 2023-09-24 19:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatapp', '0003_conversation_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conversation',
            name='active',
        ),
    ]
